CREATE EXTENSION IF NOT EXISTS "uuid-ossp";

CREATE TABLE country (
  country_code TEXT PRIMARY KEY,
  country_name TEXT NOT NULL,
  lat FLOAT,
  lng FLOAT,
  image_url TEXT
);

CREATE TABLE region (
  id INT PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
  country_code TEXT REFERENCES country(country_code) ON DELETE CASCADE,
  region_name TEXT,
  region_short TEXT,
  lat FLOAT,
  lng FLOAT,
  image_url TEXT
);

CREATE TABLE city (
  id INT PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
  city_name TEXT NOT NULL,
  city_ascii TEXT,
  lat FLOAT,
  lng FLOAT,
  country TEXT,
  country_code TEXT REFERENCES country(country_code) ON DELETE CASCADE,
  iso3 TEXT,
  admin_name TEXT,
  region_id INT REFERENCES region(id) ON DELETE SET NULL,
  capital TEXT,
  population TEXT,
  image_url TEXT
);
-- https://simplemaps.com/data/world-cities

CREATE TYPE listing_state AS ENUM (
  'Draft',
  'Private',
  'Public',
  'Flagged',
  'Banned',
  'Archived'
);

CREATE TABLE app_user (
  id uuid PRIMARY KEY DEFAULT uuid_generate_v4 (),
  token TEXT,
  image_url TEXT,
  email TEXT,
  fullname TEXT,
  username TEXT UNIQUE,
  password_digest TEXT,
  admin BOOL DEFAULT false,
  country_name TEXT,
  region_name TEXT,
  city_name TEXT,
  city_id INT REFERENCES city(id) ON DELETE SET NULL,
  user_state listing_state DEFAULT 'Public',
  created TIMESTAMPTZ DEFAULT now(),
  last_login TIMESTAMPTZ
);

CREATE TYPE flyer_type AS ENUM (
  'Show',
  'Fest',
  'Tour'
);

CREATE TABLE flyer (
  id uuid PRIMARY KEY DEFAULT uuid_generate_v4 (),
  creator_id uuid REFERENCES app_user(id) ON DELETE SET NULL,
  image_url TEXT,
  flyer_type flyer_type NOT NULL,
  headline TEXT,
  bands TEXT,
  details TEXT,
  publish_comment TEXT,
  listing_state listing_state DEFAULT 'Public',
  created TIMESTAMPTZ DEFAULT now(),
  modified TIMESTAMPTZ DEFAULT now()
);

CREATE TABLE event (
  id uuid PRIMARY KEY DEFAULT uuid_generate_v4 (),
  flyer_id uuid REFERENCES flyer(id) ON DELETE SET NULL,
  event_date DATE,
  venue_name TEXT,
  country_name TEXT,
  region_name TEXT,
  city_name TEXT,
  city_id INT REFERENCES city(id) ON DELETE SET NULL
);
