CREATE TABLE event (
  id INT PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
  creator SERIAL REFERENCES app_user(id) ON DELETE SET NULL,
  photo_url TEXT,
  event_times TEXT,
  event_name TEXT,
  description TEXT,
  start_date DATE,
  end_date DATE,
  created_at TIMESTAMP DEFAULT now(),
  updated_at TIMESTAMP DEFAULT now()
)


