CREATE TABLE venue (
   id INT PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
   venue_name TEXT,
   is_private BOOLEAN DEFAULT FALSE,
   street_address TEXT,
   postal_code TEXT,
   city_id INT REFERENCES city(id) ON DELETE NO ACTION
);
